/**
 * Fly.io multi-tenant, multi-app deployment script for the rw-server-new
 * monorepo.
 *
 * Usage:
 *   pnpm fly:generate --app api|workers <tenant>     # write fly.generated.toml
 *   pnpm fly:deploy   --app api|workers <tenant>     # generate + validate + deploy
 *
 * Tenant configs live at:
 *   apps/api/fly/base.toml      + apps/api/fly/tenants/<tenant>.toml
 *   apps/workers/fly/base.toml  + apps/workers/fly/tenants/<tenant>.toml
 *
 * Examples:
 *   pnpm fly:generate --app api sim
 *   pnpm fly:deploy   --app workers dixie
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse, stringify } from "smol-toml";

const ROOT_DIR = resolve(import.meta.dirname, "..");

interface TenantMeta {
  required_secrets?: string[];
  domain?: string;
}

type TomlValue = string | number | boolean | Date | TomlValue[] | { [key: string]: TomlValue };
type TomlObject = { [key: string]: TomlValue };

function deepMerge(base: TomlObject, override: TomlObject): TomlObject {
  const result = { ...base };
  for (const key of Object.keys(override)) {
    const baseValue = base[key];
    const overrideValue = override[key];
    if (Array.isArray(overrideValue)) {
      result[key] = overrideValue;
    } else if (
      typeof overrideValue === "object" &&
      overrideValue !== null &&
      !(overrideValue instanceof Date) &&
      typeof baseValue === "object" &&
      baseValue !== null &&
      !(baseValue instanceof Date) &&
      !Array.isArray(baseValue)
    ) {
      result[key] = deepMerge(baseValue as TomlObject, overrideValue as TomlObject);
    } else {
      result[key] = overrideValue;
    }
  }
  return result;
}

function appPaths(app: "api" | "workers"): { base: string; tenantsDir: string; out: string; dockerfile: string } {
  const appDir = resolve(ROOT_DIR, "apps", app);
  return {
    base: resolve(appDir, "fly/base.toml"),
    tenantsDir: resolve(appDir, "fly/tenants"),
    out: resolve(appDir, "fly.generated.toml"),
    dockerfile: resolve(ROOT_DIR, "Dockerfile"),
  };
}

function listTenants(tenantsDir: string): string[] {
  if (!existsSync(tenantsDir)) return [];
  return readdirSync(tenantsDir)
    .filter((f) => f.endsWith(".toml"))
    .map((f) => f.replace(".toml", ""));
}

function loadConfig(path: string): TomlObject {
  return parse(readFileSync(path, "utf-8")) as TomlObject;
}

function generate(app: "api" | "workers", tenant: string): { config: TomlObject; meta: TenantMeta; outPath: string } {
  const { base, tenantsDir, out } = appPaths(app);
  const tenantPath = resolve(tenantsDir, `${tenant}.toml`);

  if (!existsSync(base)) {
    console.error(`Error: Base config not found at ${base}`);
    process.exit(1);
  }
  if (!existsSync(tenantPath)) {
    const available = listTenants(tenantsDir);
    console.error(`Error: Tenant config not found: ${tenant}`);
    console.error(`Available tenants for app=${app}: ${available.join(", ") || "(none)"}`);
    process.exit(1);
  }

  const baseConfig = loadConfig(base);
  const tenantConfig = loadConfig(tenantPath);
  const meta = (tenantConfig._meta as TenantMeta) || {};
  delete tenantConfig._meta;

  const merged = deepMerge(baseConfig, tenantConfig);
  return { config: merged, meta, outPath: out };
}

function writeGeneratedConfig(config: TomlObject, outPath: string): void {
  const header = `# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by: pnpm fly:generate or pnpm fly:deploy
# Source: apps/<app>/fly/base.toml + apps/<app>/fly/tenants/<tenant>.toml

`;
  writeFileSync(outPath, header + stringify(config));
  console.log(`Generated: ${outPath}`);
}

function getAppName(config: TomlObject): string {
  const app = config.app;
  if (typeof app !== "string") {
    console.error("Error: No 'app' field in generated config");
    process.exit(1);
  }
  return app;
}

function validateSecrets(appName: string, requiredSecrets: string[]): void {
  if (requiredSecrets.length === 0) {
    console.log("No required secrets to validate.");
    return;
  }
  console.log(`Validating secrets for app: ${appName}`);
  let existing: string[];
  try {
    const output = execSync(`flyctl secrets list -a ${appName} --json`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    existing = (JSON.parse(output) as Array<{ name: string }>).map((s) => s.name);
  } catch {
    console.warn(`Warning: Could not fetch secrets for ${appName}. App may not exist yet.`);
    console.warn(`Required secrets: ${requiredSecrets.join(", ")}`);
    return;
  }
  const missing = requiredSecrets.filter((s) => !existing.includes(s));
  if (missing.length > 0) {
    console.error(`\nError: Missing required secrets for ${appName}:`);
    for (const s of missing) console.error(`  - ${s}`);
    console.error(`\nSet them with: flyctl secrets set -a ${appName} ${missing.map((s) => `${s}=...`).join(" ")}`);
    process.exit(1);
  }
  console.log(`All ${requiredSecrets.length} required secrets are set.`);
}

function ensureCertificate(appName: string, domain: string): void {
  console.log(`\nChecking certificate for ${domain}...`);
  try {
    const output = execSync(`flyctl certs list -a ${appName} --json`, {
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    const certs = JSON.parse(output) as Array<{ Hostname: string }>;
    if (certs.some((c) => c.Hostname === domain)) {
      console.log(`Certificate already exists for ${domain}`);
      return;
    }
  } catch {
    // continue to add
  }
  console.log(`Adding certificate for ${domain}...`);
  try {
    execSync(`flyctl certs add ${domain} -a ${appName}`, { stdio: "inherit" });
  } catch {
    console.warn(`Warning: Could not add certificate for ${domain}.`);
  }
}

function deploy(outPath: string, dockerfile: string, target: "api" | "workers"): void {
  console.log("\nDeploying to Fly.io...\n");
  execSync(`flyctl deploy --local-only -c ${outPath} --dockerfile ${dockerfile} --build-target ${target} ${ROOT_DIR}`, {
    stdio: "inherit",
  });
}

function getFlagValue(args: string[], name: string): string | undefined {
  const idx = args.indexOf(name);
  return idx !== -1 ? args[idx + 1] : undefined;
}

function main(): void {
  const args = process.argv.slice(2);
  const generateOnly = args.includes("--generate-only");

  const appArg = getFlagValue(args, "--app");
  if (appArg !== "api" && appArg !== "workers") {
    console.error(`Error: --app must be 'api' or 'workers', got: ${appArg ?? "(missing)"}`);
    process.exit(1);
  }
  const app = appArg;

  const flagValues = new Set<string>();
  for (const flag of ["--app"]) {
    const v = getFlagValue(args, flag);
    if (v !== undefined) flagValues.add(v);
  }
  const tenant = args.find((a) => !a.startsWith("--") && !flagValues.has(a));

  if (!tenant) {
    const { tenantsDir } = appPaths(app);
    const available = listTenants(tenantsDir);
    console.error(`Usage: fly-deploy [--generate-only] --app api|workers <tenant>`);
    console.error(`Available tenants for app=${app}: ${available.join(", ") || "(none)"}`);
    process.exit(1);
  }

  console.log(`\nApp: ${app}`);
  console.log(`Tenant: ${tenant}`);
  console.log(`Action: ${generateOnly ? "generate only" : "generate + deploy"}\n`);

  const { config, meta, outPath } = generate(app, tenant);
  writeGeneratedConfig(config, outPath);

  if (generateOnly) {
    console.log("\nDone (generate only mode).");
    return;
  }

  const appName = getAppName(config);
  validateSecrets(appName, meta.required_secrets ?? []);

  if (meta.domain) {
    ensureCertificate(appName, meta.domain);
  }

  const { dockerfile } = appPaths(app);
  deploy(outPath, dockerfile, app);
  console.log("\nDeployment complete!");
}

main();
